name = "menu"
name_pretty = "Menu"
fixed_order = true
icon = ""

[[entries]]
icon = ""
text = "Lock"
actions = { "lock" = "pidof hyprlock || hyprlock &" }

[[entries]]
icon = "󰤄"
text = "Suspend"
actions = { "suspend" = "systemctl suspend" }

[[entries]]
icon = "󰿅"
text = "Logout"
actions = { "relaunch" = "hyprctl dispatch exit" }

[[entries]]
icon = "󰜉"
text = "Restart"
actions = { "restart" = "systemctl reboot" }

[[entries]]
icon = "󰐥"
text = "Shutdown"
actions = { "shutdown" = "systemctl poweroff" }
